project:
  type: book
  output-dir: docs

book:
  title: "The Remarkable Diary of Thomas Russell while at Skidegate Inlet, Queen Charlotte Islands (Haida Gwaii) September 1870 – May 1871."
  author:
    - name: "Quentin Goodbody"
      affiliation: "Ladysmith and District Historical Society"
  date: 18 02 2026
  
  description: 
    <br>
    A transcribed and annotated edition of the diary of Thomas Russell documenting coal mining operations and interactions with the Haida First Nation
    in the Queen Charlotte Islands (Haida Gwaii) during the late nineteenth century.

  cover-image: img/logo.jpg

  site-url: "https://ladysmithhistoricalsociety.ca"
  repo-url: "https://github.com/tgoodbody/Thomas-Russell-Diaries"
  repo-actions: [edit, issue]

  language: en-CA

  page-navigation: true
  chapters:
    - index.qmd

    - part: "**Diary**"
      chapters:
        - diary_Volume_1.qmd
        - diary_Volume_2.qmd
        - diary_Volume_3.qmd
        - diary_Volume_4.qmd
  
    - part: "**Background**"
      chapters:
        - Thomas_Russell_and_Family.qmd
        - Discovery_of_Coal_at_Skidegate_Inlet.qmd
        - Appraisal_and_Development_of_the_Cowgitz_Coal.qmd
        
    - part: "**Geology**"
      chapters:
        - Geological_Survey_Appraisal_of_the_Cowgitz_Coal.qmd
        - Geological_Setting_of_the_Cowgitz_Coal.qmd
        
    - part: "**Appendices**"
      chapters:
      - The_Thornton.qmd
      - Augustus_Frederick_Pemberton.qmd
      - Roland_Wignall_Fawcett.qmd
      - Medical_Explanations.qmd
      - Haida_Villages_and_Chiefs.qmd
      - Dawson_Whaling_Operations.qmd
      - Wreck_of_the_Suwanee.qmd
      - Morris_Reily.qmd
      - Mifflin_Wistar_Gibbs.qmd
      - Chinook_Jargon.qmd
      - Origin_of_the_name_Cowgitz.qmd
      - Superintendents_of_the_Cowgitz_Mine.qmd
      - maps.qmd

site-url: https://www.ladysmithhistoricalsociety.ca/

number-depth: 2

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    toc-depth: 4
    link-external-newwindow: true
  
crossref:
  fig-title: "Image"
  
editor: source

